INSERT INTO [Foods]([CategoryId], [FoodName], [FoodPrice], [FoodImage], [FoodStock], [FoodDescription])
VALUES
(1, N'Mứt Cóc Cay', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148313/HNAG/Food_Mut/01.MutCocCay.jpg', 100, N'Hộp 500gr. Mứt Cóc sấy dẻo có lượng đường tự nhiên ít, chất xơ và protein cao, quả cóc còn là loại trái cây lý tưởng trong những thực đơn ăn kiêng giảm cân, nên sản phẩm sau khi chế biến vẫn giữ được nguyên hương vị, màu sắc tự nhiên, giá trị dinh dưỡng không bị biến đổi, có quy trình sản xuất đảm bảo 100% an toàn vệ sinh thực phẩm. Bạn có muốn thưởng thức cóc non theo hương vị mới lạ.'),
(1, N'Ổi Xá Lị Omai', 130000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148315/HNAG/Food_Mut/02.OiXaLiOmai.jpg', 100, N'Hộp 300gr. Ổi hồng (xá lị) sấy dẻo không đường mix muối ớt ô mai có vị cay the ngọt ngọt mằn mặn mà vẫn còn vị chua tự nhiên hòa quyện hấp dẫn, Chứa nhiều vitamin C, chất xơ và protein cao tốt cho mắt, giúp đẹp da, giảm cân, một món ăn mang đến cho bạn hương vị thơm ngon và mới lạ. Hãy cùng bạn bè thưởng thức nhâm nhi món ổi hồng mix muối ớt ngon đậm vị thật đặc trưng. Bạn có muốn thưởng thức món ăn được nhiều người yêu thích.'),
(1, N'Mít Viên Sấy Dẻo', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148316/HNAG/Food_Mut/03.MitVienSayDeo.jpg', 100, N'Hộp 500gr. Mít Sấy Dẻo có màu vàng tươi, vị ngọt đậm, dẻo vừa ăn thơm lừng mùi mít chín cây thơm ngon và hấp dẫn khẩu vị mà còn cung cấp nhiều chất dinh dưỡng\n- Sấy dẻo 100% tự nhiên, không phẩm màu, không hoá chất, màu sắc và hương vị tự nhiên, quy trình sản xuất đảm bảo an toàn vệ sinh thực phẩm. \n- Đảm bảo đạt tiêu chuẩn an toàn vệ sinh thực phẩm, mà còn giữ nguyên độ ẩm, dưỡng chất của trái cây tự nhiên.'),
(1, N'Mứt Mãng Cầu Me', 140000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148317/HNAG/Food_Mut/04.MutMangCauMe.jpg', 100, N'Hộp 500gr. Mứt Mãng cầu me chua chua, ngọt ngọt, thơm ngon vẫn giữ nguyên hương vị tự nhiên của trái mãng cầu và trái me.'),
(1, N'Mứt Mãng Cầu Xiêm', 140000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148318/HNAG/Food_Mut/05.MutMangCauXiem.jpg', 100, N'Hộp 500gr. Mãng cầu sấy dẻo được làm từ 100% mãng cầu xiêm tươi nguyên trái, sản phẩm được tách hạt, cô đặc thành miếng, không sử dụng hóa chất và phụ gia thực phẩm, an toàn cho sức khỏe người sử dụng.'),
(1, N'Thơm Rim Muối Omai', 130000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148320/HNAG/Food_Mut/06.ThomRimMuoiOmai.jpg', 100, N'Hộp 300gr. Thơm sấy muối ớt ăn giòn dẻo vị chua cay ngọt mặn hòa quyện hấp dẫn. Tất cả đều là những nguyên liệu quen thuộc phối hợp vô cùng độc đáo. Hãy cùng bạn bè thưởng thức nhâm nhi món mãng cầu mix muối ớt ngon đậm vị thật đặc trưng. Bạn có muốn thưởng thức món ăn được nhiều người yêu thích.'),
(1, N'Mãng Cầu Sấy Muối Ớt ', 200000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148321/HNAG/Food_Mut/07.MangCauSayMuoiOt.jpg', 100, N'Hộp 500gr. Mãng Cầu sấy muối ớt ăn dai dẻo vị chua cay ngọt mặn hòa quyện hấp dẫn, Tất cả đều là những nguyên liệu quen thuộc phối hợp vô cùng độc đáo. Hãy cùng bạn bè thưởng thức nhâm nhi món mãng cầu mix muối ớt ngon đậm vị thật đặc trưng. Bạn có muốn thưởng thức món ăn được nhiều người yêu thích.'),
(1, N'Mứt Sơ Ri Sấy Dẻo ', 110000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148322/HNAG/Food_Mut/08.SoRiSayDeo.webp', 100, N'Hộp 500gr. Mứt Sơ Ri với vị chua ngọt tự nhiên, không chất bảo quản, không chất phụ gia. Sản phẩm được kiểm tra định kỳ nên các bạn hoàn toàn yên tâm về chất lượng. Sản phẩm được phơi trong nhà kín luôn sạch sẽ, không sợ bụi và côn trùng. Có độ ngọt vừa, dẻo, vị chua của sơ ri nên không gây cảm giác ngán. Có thể dùng ngay hoặc làm cocktails'),
(1, N'Mứt Me Sấy Muối Ớt', 110000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148323/HNAG/Food_Mut/09.MutMeMuoiOi.jpg', 100, N'Hộp 500gr. Me sấy muối ớt ăn dai dẻo vị chua cay ngọt mặn hòa quyện hấp dẫn, Tất cả đều là những nguyên liệu quen thuộc phối hợp vô cùng độc đáo. Hãy cùng bạn bè thưởng thức nhâm nhi món me trái mix muối ớt ngon đậm vị thật đặc trưng. Bạn có muốn thưởng thức món ăn được nhiều người yêu thích.'),
(1, N'Mứt Thốt Nốt Dẻo', 140000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148324/HNAG/Food_Mut/10.ThotNotSayDeo.jpg', 100, N'Hộp 500gr. Thốt nốt sấy dẻo có hương vị ngọt dịu vừa thơm lại có độ dẻo dẻo dai dai ăn rất vui miệng, vẫn giữ nguyên được mùi vị và giá trị dinh dưỡng thích hợp để bổ sung khẩu phần dinh dưỡng cho trẻ em và người già mỗi ngày. Với qui trình sấy 100% tự nhiên, không phẩm màu, không hoá chất, màu sắc và hương vị tự nhiên, đảm bảo an toàn vệ sinh thực phẩm, được đóng gói tiện dụng, thuận lợi mang theo mỗi khi đi xa hay dành làm quà tặng.')
