INSERT INTO [Foods]([CategoryId], [FoodName], [FoodPrice], [FoodImage], [FoodStock], [FoodDescription])
VALUES
(2, N'Kẹo Phồng Mít Dừa Non', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145861/HNAG/Food_Keo/01.KeoPhongMitDuaNon.jpg', 100, N'Hộp 500gr. Kẹo Mít Dừa Non có vị ngọt tự nhiên và thơm nhẹ nhàng của mít mà khi ăn lại có độ dẻo béo của dừa non kết hợp với lớp bánh tráng mỏng giòn xốp bên ngoài làm nên hương vị đậm đà của viên kẹo đặc sản từ Bến Tre.'),
(2, N'Kẹo Phồng Chuối Dừa Non', 120000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145863/HNAG/Food_Keo/02.KeoPhongChuoiDuaNon.jpg', 100, N'Hộp 500gr. Kẹo Chuối Dừa Non là sự hoà quyện giữa vị cay cay của gừng, thoang thoảng mùi thơm của chuối chín và vị bùi bùi của đậu phộng cùng với vị béo của dừa non. Kẹo Chuối Cuộn Gừng Đậu Phộng Dừa Non được làm từ trái chuối xiêm chín cây, đường cát, nước cốt dừa và mạch nha tạo nên món kẹo dẻo dẻo, dai dai và ăn rất ngon. Kẹo chuối với bao bì riêng biệt từng viên kẹo giúp bảo quản tốt hơn.'),
(2, N'Kẹo Đậu Phộng Xốp bơ', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145864/HNAG/Food_Keo/03.KeoDauPhongXopBo.jpg', 100, N'Gói 500gr. Kẹo đậu phộng là món đặc sản dân dã và được rất nhiều người yêu thích nhưng nếu bạn chưa thử qua món kẹo đâu phộng thì sẽ là thiếu sót lớn bởi hương vị kẹo rất ngon, rất lạ và không quá ngọt bạn có thể nếm lai rai hoài mà không hề ngán.'),
(2, N'Kẹo Khóm Cuộn', 110000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145865/HNAG/Food_Keo/04.KeoKhomCuon.jpg', 100, N'Hộp 500gr. Kẹo khóm cuộn tắc được bọc lớp bánh tráng giòn, vẫn giữ trọn vị chua và thơm của khóm tươi, thêm đậu phộng thơm béo.'),
(2, N'Kẹo Chuối Mè Gừng', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145867/HNAG/Food_Keo/05.KeoChuoiMeGung.jpg', 100, N'Hộp 500gr. Kẹo chuối được làm từ chuối xiêm chín, đường, nước cốt dừa và mạch nha tạo nên món kẹo dẻo dẻo, dai dai và ăn rất ngon , đây là món kẹo đặc sản của làng nghề truyền thống Bến Tre. Kẹo chuối tươi với bao bì riêng biệt từng viên giúp bảo quản tốt hơn và ăn ngon hơn.'),
(2, N'Kẹo Dồi Lạc', 110000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145868/HNAG/Food_Keo/06.KeoDoiLac.jpg', 100, N'Hộp 500gr. Kẹo dồi được tạo hình thành từng thanh kẹo trắng tinh, bên trong là nhân đậu phộng đã được rang chín thơm. Mùi vani thoang thoảng, được làm đặc sản để gửi đi khắp mọi miền Tổ quốc nhưng vẫn giữ được độ giòn rôm rốp.'),
(2, N'Kẹo Chuối Tươi', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145869/HNAG/Food_Keo/07.KeoChuoiTuoi.jpg', 100, N'Bịch 500gr. Kẹo chuối tươi được làm từ chuối xiêm chính, đường, nước cốt dừa và mạch nha tạo nên món kẹo dẻo dẻo, dai dai và ăn rất ngon , đây là món kẹo đặc sản của làng nghề truyền thống Bến Tre'),
(2, N'Kẹo Chuối Tươi Cốt Dừa', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145870/HNAG/Food_Keo/08.KeoChuoiTuoiCotDua.webp', 100, N'Hộp 500gr. Kẹo chuối có vị béo rất đậm đà do có nhiều nước cốt dừa hơn trong công thức chế biến, có vị ngọt thanh (ít ngọt) nên ăn nhiều mà không gây ngán (ngấy). Đóng gói dây chuyền tự động, từng viên kẹo được bọc riêng bằng giấy kiếng, nên đảm bảo vệ sinh an toàn thực phẩm, vừa có thể bảo quản tốt hơn cũng như giữ được hương vị thơm ngon lâu hơn.'),
(2, N'Kẹo Me', 80000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145870/HNAG/Food_Keo/09.KeoMe.jpg', 100, N'Hộp 300gr. Kẹo me luôn được các bạn trẻ thích thú vì có sự hòa quyện nhiều hương vị trong đó. Chỉ cần ngậm một miếng kẹo và nhắm mắt lại, cảm giác khoan khoái sẽ lan khắp các vị giác. Món ăn vặt ưa thích, thích hợp tiêu dùng hoặc làm quà tặng. Hương vị thơm ngon, độ ngọt vừa phải.'),
(2, N'Kẹo Dừa Non', 115000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145873/HNAG/Food_Keo/10.KeoDuaNon.jpg', 100, N'Hộp 500gr. Kẹo Dừa Dứa Non Lá Dứa được làm từ cùi dừa non của quả dừa Xiêm Dứa một loại dừa vô cùng đặc biệt, tuy trái nhỏ nhưng nước ngọt và thơm mùi lá sâm dứa đặc trưng. Vì thế kẹo dừa dứa non mềm dẻo và thơm ngậy vị dừa dứa rất ngon và lạ miệng.')
