INSERT INTO [Foods]([CategoryId], [FoodName], [FoodPrice], [FoodImage], [FoodStock], [FoodDescription])
VALUES
(3, N'Bánh Trung Thu Thập Cẩm', 170000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142235/HNAG/Food_Banh/01.BanhTrungThuThapCamGaQuay.jpg', 100, N'Hộp 2 bánh. Bánh trung thu (moon cake) là loại bánh nướng quen thuộc trong mỗi dịp Tết Trung Thu. Bánh truyền thống có hình tròn, hình vuông với nhân ngọt từ đậu xanh và thập cẩm. Ngày nay, bánh được biến tấu đa dạng như bánh dẻo, bánh chay, rau câu với các nhân mới lạ như cà phê, socola, trái cây, bào ngư, trứng muối, sò điệp..'),
(3, N'Bánh Gấu Nhân Kem', 90000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142236/HNAG/Food_Banh/02.BanhGauNhanKem.jpg', 100, N'Bịch 500gr. Bánh gấu nhân kem vị kem béo, ít ngọt, thơm ngon, bánh giòn.Bánh gấu là món ăn vặt hấp dẫn mọi lứa tuổi, mềm dễ ăn, Bánh ăn liền nên thích hợp dùng trong sinh nhật, picnic, hội họp, lễ, tết…hay đơn giản nhâm nhi và xem phim, tụ họp nhóm ăn vặt.'),
(3, N'Bánh Rong Biển Chà Bông', 125000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142238/HNAG/Food_Banh/03.BanhRongBienChaBong.jpg', 100, N'Túi 250gr. Bánh tráng rong biển là sản phẩm nằm trong TOP những loại đặc sản nổi tiếng tại Bình Định. Đây cũng chính nơi đã sản sinh ra nhiều loại bánh tráng phổ biến khác, thường hay xuất hiện trong các bữa ăn của người Việt như: bánh tráng gạo mè, bánh tráng mì, bánh tráng cuốn gỏi,… Còn bây giờ hãy cùng Sachi đi tìm hiểu rõ hơn về sản phẩm này, cũng như nơi bán bánh tráng rong biển chính hiệu Bình Định nhé !'),
(3, N'Bánh Bao Sữa', 30000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142239/HNAG/Food_Banh/04.BanhBaoSua.jpg', 100, N'Xâu 10 gói. Bánh bao sữa là một món ăn bố dưỡng và hấp dẫn đối với tất cả mọi người. Những chiếc bánh trắng ngần, thơm phức mùi sữa đã khiến bao người không thể chối từ ngay từ cái nhìn đầu tiên.'),
(3, N'Chả Giò Tôm Mini', 90000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142240/HNAG/Food_Banh/05.ChaGioTomMini.jpg', 100, N'Hũ 250gr. Snack chả giò tôm mini. Nhân tôm thịt đậm đà, vị giòn tan rôm rốp ăn cực đã. Món này thích hợp đi xem phim, ăn vặt mọi lúc mọi nơi đều được luôn nà.'),
(3, N'Bánh Gấu Mix 4 vị', 90000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142677/HNAG/Food_Banh/06.BanhGauMix4Vi.jpg', 100, N'Hộp 450gr. Bánh gấu nhân kem ngon tuyệt, luôn hấp dẫn từ xưa đến nay.Vị kem béo, ít ngọt, thơm ngon. Bánh gấu là món ăn vặt từ trẻ nhỏ đến người lớn tuổi ai cũng đều thích thú khi cầm miếng bánh lên và thưởng thức.'),
(3, N'Bánh Mì Bơ Sấy Ruốc', 120000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142678/HNAG/Food_Banh/07.BanhMiBoSayRuoc.webp', 100, N'Gói 420gr. Bánh mì chà bông sốt dầu trứng vừa mềm vừa dai, thơm mùi bơ và có chút mằn mặn. Bánh rất thích hợp để bạn dùng vào buổi sáng hoặc buổi chiều vừa tiện lợi vừa bổ dưỡng.'),
(3, N'Bánh Ống Ngò Nhân Đậu Phộng', 95000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142241/HNAG/Food_Banh/08.BanhOngNgoNhanDauPhong.jpg', 100, N'500gr. Lớp vỏ bánh giòn tan hoà với vị béo ngậy của bơ đậu phộng,hương thơm của ngò rí,mặn mặn ngọt ngọt kết hợp hài hoà với nhau. Bánh này ăn chơi nhâm nhi cùng tách cà phê hay trà cũng thú vị lắm luôn nè.'),
(3, N'Bánh Dừa Sầu Riêng', 80000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142242/HNAG/Food_Banh/09.BanhDuaSauRieng.jpg', 100, N'Hộp 300gr. Bánh không ngọt gắt, thơm mùi cơm dừa xào với sầu riêng và mè, và với kĩ thuật nướng bánh nhìu năm vỏ bánh mỏng, giòn tan không quá dày.'),
(3, N'Bánh Kẹp CaCao', 110000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681142243/HNAG/Food_Banh/10.BanhKepCaCao.jpg', 100, N'Hũ 500gr. Bánh kẹp cacao nhân kem cacao, mùi thơm cacao, lớp bánh giòn tan, ngọt nhẹ nhàng thanh tao cùng lớp nhân cacao thơm phứt béo ngậy...')