INSERT INTO [Foods]([CategoryId], [FoodName], [FoodPrice], [FoodImage], [FoodStock], [FoodDescription])
VALUES
(4, N'Cơm Cháy Mini - Chà Bông', 65000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145074/HNAG/Food_ComChay/01.ComChayMiniChaBong.webp', 100, N'Bịch 250gr. Cơm cháy chà bông là loại thực phẩm ăn nhanh ngon miệng, không chỉ trẻ em mà người lớn cũng rất thích món ăn này.'),
(4, N'Cơm Cháy Đáy Nồi - Chà Bông', 130000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145077/HNAG/Food_ComChay/02.ComChayDayNoiChaBong.jpg', 100, N'Bịch 500gr. Cơm cháy đáy nồi, món bim bim tuổi thơ ăn "méo mồm" nhưng dân mạng đều thèm thuồng, thời nay mấy khi còn được ăn.'),
(4, N'Cơm Cháy Siêu Chà Bông', 65000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145079/HNAG/Food_ComChay/03.ComChaySieuChaBong.jpg', 100, N'Bịch 250gr. Cơm cháy được sản xuất bằng công thức gia truyền, nguyên liệu sạch, đảm bảo về độ giòn, thơm, không hôi dầu, chà bông là loại thịt tươi ngon, đảm bảo vệ sinh an toàn thực phẩm, chà bông thịt 100%, không pha trộn.'),
(4, N'Cơm Cháy Trứng Muối - Chà Bông', 80000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145081/HNAG/Food_ComChay/04.ComChayTrungMuoi.jpg', 100, N'Bịch 250gr. Cơm cháy trứng muối vàng tươi nướng tới được giã nhuyễn rắc đều lên bề mặt miếng cơm cháy đã cho đều nước mắm và gia vị chắc chắn lần đầu ăn sẽ không cưỡng lại độ giòn béo thơm của món cơm cháy đặc biệt này đem lại.'),
(4, N'Cơm Cháy Sốt Nước Mắm ', 110000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145082/HNAG/Food_ComChay/05.ComChaySotNuocMam.jpg', 100, N'Bịch 500gr. Cơm cháy nước mắm và cơm cháy chà bông là 2 món ăn vặt khoái khẩu, giòn cay với vị giòn rụm của nếp chiên, nước mắm thơm thơm cay cay hấp dẫn.'),
(4, N'Cơm Cháy Chiên Nước Mắm', 10000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145085/HNAG/Food_ComChay/06.ComChayChienNuocMam.jpg', 100, N'Bịch 3 miếng. Cơm cháy chiên nước mắm luôn là một trong những món ăn vặt dân gian khoái khẩu, với hương vị giòn giòn, cay cay, đậm đà mùi nước mắm kèm với mỡ hành làm biết bao nhiêu tín đồ mê ăn vặt say đắm.'),
(4, N'Cơm Cháy Lắc Phô Mai', 80000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145089/HNAG/Food_ComChay/07.ComChayLacPhoMai.webp', 100, N'Bịch 250gr. Một trong những món ăn vặt “sốt xình xịch” của nhà RỤM mà bạn không thể bỏ qua chính là phiên bản cơm cháy chà bông phô mai - món ngon trẻ mê, bao nhiêu cũng hết. Hãy cùng kéo ngay xuống bên dưới để tìm hiểu ngay về món ăn vặt đặc biệt của cơm cháy rụm này nhé!'),
(4, N'Cơm Cháy  Lắc Khô Gà', 60000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145091/HNAG/Food_ComChay/08.ComChayKhoGa.webp', 100, N'Hộp 350gr. Cơm cháy  được dùng từ cơm cháy nguyên miếng trong bịch, không sử dụng loại cơm bể vụn để luôn đảm bảo được độ giòn mới của cơm cháy. Khô gà được dùng là khô gà loại 1 không quá khô cứng, độ mềm vừa phải không quá ướt đảm bảo khi kết hợp cùng cơm cháy chiên nước mắm thành món cơm cháy khô gà hoàn hảo.'),
(4, N'Cơm Cháy Gạo Lứt Chà Bông ', 70000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145094/HNAG/Food_ComChay/09.ComChayGaoLutChaBong.jpg', 100, N'Gói 200gr. Gạo lứt được biết đến là loại thực phẩm có tác dụng rất tốt cho sức khỏe. Đặc biệt cung cấp lượng lớn chất xơ và các vitamin, khoáng chất quan trọng, cần thiết cho cơ thể. Tuy nhiên, vì gạo có tính chất thô cứng, nhai có cảm giác lạo xạo nên khi dùng trong bữa ăn thông thường sẽ dễ có cảm giác ngán ăn, không muốn ăn.'),
(4, N'Cơm Cháy Rong Biển Chà Bông', 80000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681145097/HNAG/Food_ComChay/10.ComChayRongBienChaBong.jpg', 100, N'Gói 250gr. Rong biển là một loại thực phẩm giàu chất xơ, các khoáng chất, các vitamin cần thiết cho cơ thể và hàm lượng iốt vừa đủ. Chẳng những thế, rong biển còn mang nhiều tác dụng tuyệt vời như: cải thiện sức khỏe tim mạch, giảm cân, tăng cường hệ miễn dịch, giảm nguy cơ ung thư và ngăn ngừa các loại bệnh khác.')
