INSERT INTO [Foods]([CategoryId], [FoodName], [FoodPrice], [FoodImage], [FoodStock], [FoodDescription])
VALUES
(5, N'Bánh Tráng Ống Chấm Me', 120000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144435/HNAG/Food_BanhTrang/01.BanhTrangOngChamMe.jpg', 100, N'Set 450gr. Bánh tráng ống chấm me được làm từ bánh tráng tốt nhất và ăn kèm với đậu phộng, hành phi cho mùi vị ngon nhất có thể, chấm với sốt me chua chua ngọt ngọt đảm bảo bạn thích ngay lần đầu tiên'),
(5, N'Bánh Tráng Nướng Mắm Ruốc', 55000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144436/HNAG/Food_BanhTrang/02.BanhTrangNuongMamRuoc.webp', 100, N'Bịch 5 cái. Bánh tráng nướng mắm ruốc là món ăn vặt được yêu thích của giới trẻ hiện nay. Bánh tráng nướng giòn tan, thêm trứng cút, chả lụa, nem chua, bơ, mắm ruốc hòa quyện.'),
(5, N'Set Bánh Tráng Chấm', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144439/HNAG/Food_BanhTrang/03.BanhTrangCham.webp', 100, N'Set 350gr. Thú vui thưởng thức món ăn này là vừa xé từng miếng bánh tráng dai dai rồi chấm mút, cảm nhận từng tầng hương vị giao hòa trọn vẹn.'),
(5, N'Bánh Tráng Lá chuối', 35000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144441/HNAG/Food_BanhTrang/04.BanhTrangLaChuoi.webp', 100, N'Hũ 100gr. Bánh tráng này được phơi trong sương đêm, đủ mềm và dẻo, chẳng cần ủ lá chuối, dùng cuốn bánh hay cuốn thịt, cuốn rau, cuốn cá hấp đều được. Bánh tráng ủ lá chuối làm cho bánh tráng dẻo, mềm, thơm, mang theo hương gạo, ăn rất ngon và tuyệt.'),
(5, N'Bánh Tráng Sate Tôm', 45000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144442/HNAG/Food_BanhTrang/05.BanhTrangSateTom.jpg', 100, N'Gói 150gr. Bánh tráng sa tế là một món ăn vặt được giới trẻ đặc biệt yêu thích. Đặc biệt là các chị em và các bạn học sinh, sinh viên. Bánh tráng trộn sa tế là món ăn hấp dẫn, thu hút người thưởng thức không chỉ bởi hương vị mà còn là ở màu sắc bắt mắt và giá trị ẩm thực của món ăn.'),
(5, N'Set Bánh Tráng Ớt Rim Mật Ong', 110000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144443/HNAG/Food_BanhTrang/06.BanhTrangOtRimMatOng.webp', 100, N'Set 200gr. Bánh tráng Ớt rim mật ong siêu cay, nguyên liệu gồm muối, tắc, ớt tươi, mật ong, hứa hẹn đem tới cho bạn món ăn vặt mới mẻ.'),
(5, N'Bánh Tráng Rong Biển', 105000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144446/HNAG/Food_BanhTrang/07.BanhTrangRongBien.jpg', 100, N'Hũ 350gr. Rong biển sấy thơm ngon, giàu dinh dưỡng đã trở thành món vặt mà nhiều bạn trẻ ưa thích hiện nay, thì giờ đây lại càng hấp dẫn hơn khi được trộn với miếng bánh tráng mềm mềm dai dai, thêm chút hương thơm của tỏi sấy, khiến cho mùi vị của chúng hòa quyện vào nhau và tan ra trong miệng khi thưởng thức, sẽ làm thoả mãn cho cơn thèm ăn vặt của bạn.'),
(5, N'Bánh Tráng Nướng Khô Bò', 55000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144447/HNAG/Food_BanhTrang/08.BanhTrangNuongKhoBo.jpg', 100, N'Bịch 10 cái. Bánh tráng được tẩm ướp gia vị, hành lá, tép cắt nhỏ rồi cuộn lại cắt thành miếng vừa ăn.Vừa giữ được những miếng khô bò, trộn đều trong từng miếng bánh, vừa thấm đượm gia vị ăn rất ngon.Sản phẩm có vị hơi cay và một ít ngọt bạn nhé.Hãy dùng thử sản phẩm và cảm nhận hương vị của từng miếng bánh tráng ạ.'),
(5, N'Bánh Tráng Bơ Tỏi', 25000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144449/HNAG/Food_BanhTrang/09.BanhTrangBoToi.jpg', 100, N'Bịch 100gr. Phần nhân bánh tráng bơ tỏi gồm có hành phi, tỏi, ruốc sấy, đậu phộng rang, trứng cút luộc. Tấm bánh tráng được cắt thành sợi to hoặc nhỏ tùy theo ý thích của bạn. Sau đó nêm xì dầu và ớt đã cắt nhỏ vào cùng bơ tỏi đã phi thơm, đun lên. Đổ sốt ra ngoài cho đỡ nóng rồi cho bánh tráng cùng các nguyên liệu vào trộn lên, bạn sẽ có một suất bánh tráng bơ tỏi cực kỳ hấp dẫn.'),
(5, N'Bánh Tráng Cuộn Thập Cẩm', 80000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681144450/HNAG/Food_BanhTrang/10.BanhTrangCuonThapCam.jpg', 100, N'Gói 500gr. Bánh tráng thập cẩm là một món ăn khá quen thuộc, không chỉ là một món ăn đường phố mà nó còn trở thành đặc sản của nhiều vùng miền như Tây Ninh, Phú Quốc… bởi những hương vị và công thức khác nhau. Mỗi sản phẩm không đơn thuần là món ăn vặt thông thường mà nó còn mang những dư vị đặc trưng của mỗi địa phương.')