INSERT INTO [Foods]([CategoryId], [FoodName], [FoodPrice], [FoodImage], [FoodStock], [FoodDescription])
VALUES
(6, N'Xí Muội Đào', 65000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148925/HNAG/Food_XiMuoiMe/01.XiMuoiDao.jpg', 100, N'Hộp 250gr. Đào bao tử hay còn gọi là đào hồng, vì chúng được tách hạt màu sắc cho bắt mắt. Vị của loại ô mai này sẽ thiên về ngọt nhiều hơn, ít chua. Ô mai này cục kỳ thích hợp cho tín đồ thích ăn đồ ngọt. Vị đào sần sật, thơm thơm. vị đường chua ngọt bắt mắt, luôn là xí muội nịnh mắt người mua.'),
(6, N'Xí Muội Mặn', 170000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148926/HNAG/Food_XiMuoiMe/02.XiMuoiMan.jpg', 100, N'Hũ 500gr. Ngày nay ô mai hay xí muội thường được xem như một hàng quà ăn chơi như mứt, kẹo được nhiều người sử dụng, ưa chuộng và mua biếu cho những người thân trong gia đình.'),
(6, N'Xí Muội Oliu', 65000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148928/HNAG/Food_XiMuoiMe/03.XiMuoiOliu.jpg', 100, N'Hộp 250gr. Xí Muội Ô Liu là một trong những loại mứt thông dụng, mà nhiều người biết tới, Ô Liu không những có vị ngọt nhẹ, mà còn kèm vị chua chua mặn mặn của Xí Muội, dễ dàng sử dụng.'),
(6, N'Xí Muội Trần Bì', 110000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148929/HNAG/Food_XiMuoiMe/04.XiMuoiTranBi.jpg', 100, N'Hộp 500gr. Trần bì xí muội được làm từ vỏ cam, quýt trộn đều với với đường và muối nên có mùi rất thơm và ngon. Công dụng chính từ trần bì xí muội: Chữa ho có đờm, viêm phế quản. Chữa chứng ho mất tiếng. Chữa ho kèm khô họng, đau cổ. Chữa viêm phế quản. Điều trị viêm phế quản cấp tính. Chữa viêm phế quản mãn tính. Chữa viêm tuyến vú. Trị chứng nôn do lạnh'),
(6, N'Me Lào Muối Ớt', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148930/HNAG/Food_XiMuoiMe/05.MeLaoMuoiOt.webp', 100, N'Hộp 500gr. Me Lào là một loại me mà phần vỏ của chúng được lột sạch phần sau đó được đem đi phơi một nắng sau đó được đem đi đóng hộp và bảo quản. Vì me Lào được được phơi một nắng nên hương vị và độ mềm của me vẫn giữ lại được. Me lào có vị ngọt và chút vị chút vị chua, phần thịt của me lào nhiều, hạt nhỏ.'),
(6, N'Me Lào Muối Tôm', 95000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148931/HNAG/Food_XiMuoiMe/06.MeLaoMuoiTom.jpg', 100, N'Hộp 500gr. Me lào được sấy lột vỏ và phơi qua 1 nắng rồi Bếp đóng hộp kèm bịch muối tôm siêu ngon. Me lào Bếp trái nhỏ, hột nhỏ ăn có độ chua ngon hơn các trái me to ạ. Cả nhà ăn chấm kèm muối tôm là chuẩn luôn đó ạ.'),
(6, N'Me Xí Muội Chùm Ruột', 110000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148932/HNAG/Food_XiMuoiMe/07.MeXiMuoiChumRuot.jpg', 100, N'Hộp 500gr. Me Xí Muội Chùm Ruột, Mỗi viên me đều có thêm 1 trái mứt chùm ruột  lạ mà ngon đặc biệt hơn me xí muội nhiều vị me dẻo chua cay mặn ngọt hoà quyện vào viên me,ăn hết viên này chỉ muốn ăn tiếp viên khác'),
(6, N'Me Rim Muối Ớt', 120000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148933/HNAG/Food_XiMuoiMe/08.MeRimMuoiOt.jpg', 100, N'Hộp 500gr. Me vị chua chua rim với muối ớt chuẩn xịn Tây Ninh 100% , những quả me to mọng được rim với muối ớt khi cắn từng miếng có độ chua ngọt cay hoà quyện khó tả'),
(6, N'Trái Say Muối Ớt', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148935/HNAG/Food_XiMuoiMe/09.TraiSayMuoiOt.jpg', 100, N'Hộp 300gr. Trái say được chế biến rất công phu, lột vỏ tỉ mỉ từng trái say rồi sau đó trộn gia vị đường, muối, ớt để khách ăn vẫn cảm nhận được nguyên vẹn vị tự nhiên của trái say'),
(6, N'Trái Say Rim Đường', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681148936/HNAG/Food_XiMuoiMe/10.TraiSayRimDuong.jpg', 100, N'Hộp 300gr. Say rim là một trong những đặc sản nổi tiếng các tỉnh duyên hải miền trung, trong đó có Ninh Thuận. Say rim ăn chua chua, ngọt ngọt rất đặc trưng mà không thể nhầm lẫn với bất kỳ với loại trái cây nào khác. Nếu đã thưởng thức một lần đặc sản này, tin chắc các bạn sẽ không thể nào quên được')