INSERT INTO [Foods]([CategoryId], [FoodName], [FoodPrice], [FoodImage], [FoodStock], [FoodDescription])
VALUES
(7, N'Khô Bò Sốt Chanh', 170000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147271/HNAG/Food_ThitKho/01.KhoBoSotChanh.jpg', 100, N'Hộp 300gr. Khô bò sốt chanh được làm từ bò miếng mềm quét sốt chanh sấy cho ráo dẻo phần sốt và thấm dày trong từng xới thịt của bò, hãy xé và xé nhỏ từng miếng quếch miếng sốt bơ ta nhâm nhi, chu choa vị khô bò vị sốt chanh hoà tan cùng sốt bơ chỉ biết nhâm nhi mà nói nó ngon quá trời.'),
(7, N'Khô Bò Giòn Cay', 320000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147273/HNAG/Food_ThitKho/02.KhoBoGionCay.jpg', 100, N'Bịch 500gr. Khô bò miếng lớn sấy giòn là món ăn vặt ngon đươc nhiều người yêu thích. Khô bò được làm 100% từ bò tươi nên miếng bò to rất đặc biệt tẩm gia vị cho vào lò sấy khô mang lại hương vị đậm đà khi ăn sẽ cảm nhận được vị thịt tươi ngay từ miếng đầu tiên, khô bò giòn rụm, cay nhẹ, thơm ngon đến từng xớ thịt, vị ướp vừa miệng.'),
(7, N'Khô Bò Vụn', 270000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147274/HNAG/Food_ThitKho/03.KhoBoVun.jpg', 100, N'Bịch 500gr. Khô bò vụn, hương vị thơm ngon như bò miếng, thơm, dù nhỏ tí nhưng ăn vẫn ngon tuyệt. Hương vị thơm ngon, không bị cứng và khô, thơm nức mùi bò, đậm đà vị tỏi ớt thích hợp cho bạn làm món nhậu, mua về làm quà cho người thân và bạn bè. Làm từ nguyên liệu thịt bò phi lê tươi ngon có thớ thịt đùi săn chắc nguyên chất 100%'),
(7, N'Khô Bò Viên', 320000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147275/HNAG/Food_ThitKho/04.KhoBoVien.jpg', 100, N'Hũ 500gr. Khô Bò Viên được sấy khô bằng công nghệ khép kín vẫn giữ được hương vị tự nhiên, bò viên dai mà không khô cứng.  Hương vị đậm đà hòa quyện cùng chút ớt cay cay và vị ngọt sẵn có; tất cả cân bằng tạo nên mùi vị cuốn hút vô cùng.'),
(7, N'Khô Bò Tỏi Ớt', 140000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147276/HNAG/Food_ThitKho/05.KhoBoToiOt.jpg', 100, N'Bịch 250gr. Dùng thịt thăn và thịt đùi và gân bò để làm khô bò là những phần ngon nhất của bò để làm nên khô bò. Bò miếng được tẩm vị vừa ăn. Cay mặn ngọt hoà quyện vào nhau nên ăn rất ngon. Ăn ngon hơn nếu dùng chanh vắt vào khô bò. Lúc đó khô bò thêm vị chua chua thấm vào miếng thịt bò ăn là quên lối về luôn…'),
(7, N'Khô Bò Que', 170000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147277/HNAG/Food_ThitKho/06.KhoBoQue.jpg', 100, N'Hộp 250gr. Khô bò que được làm từ phần thịt bò phile tươi nên từng thớ thịt đều vô cùng săn chắc, được tẩm ướp từ những gia vị tự nhiên như nghệ, gừng, muối, ớt, ngũ vị hương, dầu… không trộn, không pha, không phẩm màu nên rất an toàn với sức khỏe người sử dụng.'),
(7, N'Khô Gà Lá Chanh', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147279/HNAG/Food_ThitKho/07.KhoGaLaChanh.jpg', 100, N'Hũ 300gr. Khô gà lá chanh là một trong những “mồi nhậu” khá được lòng giới trẻ. Không cần phải đi đâu xa, chỉ cần ngồi ngay tại nhà là bạn vẫn có thể thưởng thức món khô gà lá chanh vừa thơm ngon vừa an toàn.'),
(7, N'Khô Gà Bơ Tỏi', 180000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147280/HNAG/Food_ThitKho/08.KhoGaBoToi.jpg', 100, N'Hũ 500gr. Khô gà sau khi hoàn thành có màu vàng cam đẹp mắt, thơm thoang thoảng mùi bơ cùng vị mặn ngọt, cay cay quyện chút bùi bùi từ tỏi chiên, nếm thử 1 miếng thôi cũng đủ khiến bạn thích mê.'),
(7, N'Khô Bò Ướt', 170000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147281/HNAG/Food_ThitKho/09.KhoBoUot.jpg', 100, N'Gói 200gr. Thịt bò khô là món ăn vặt quen thuộc của nhiều gia đình Việt. Ngoài món thịt bò khô xé sợi truyền thống thì món thịt bò khô ướt cũng rất được ưa chuộng với cách làm đơn giản hơn nhưng vẫn ngon không kém. Nếu bạn đang muốn tự tay làm đồ ăn đãi khách dịp Tết này thì đừng bỏ qua.'),
(7, N'Khô Bò Một Nắng', 320000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147282/HNAG/Food_ThitKho/10.KhoBoMotNang.jpg', 100, N'Bịch 500gr. Bò một nắng, đặc sản của Phố núi Gia Lai là món ăn được rất nhiều người yêu thích, đặc biệt là trên những bàn nhậu. Mặc dù món ăn có phần hơi cứng một chút nhưng khi dùng, mùi thơm của thịt bò quyện vào mùi cay nồng của nước chấm sẽ tạo nên một hương vị thơm lừng khó lẫn vào đâu được, chỉ ngửi thôi cũng đã thấy ngon.')