INSERT INTO [Foods]([CategoryId], [FoodName], [FoodPrice], [FoodImage], [FoodStock], [FoodDescription])
VALUES
(8, N'Khô Mực Hấp Nước Dừa', 140000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147768/HNAG/Food_KhoMuc/01.KhoMucHapDua.jpg', 100, N'Hộp 300gr. Món khô mực hấp nước dừa khi hoàn thành phảng phất một mùi thơm vô cùng ngọt ngào đặc trưng luôn. Khi thưởng thức, bạn có thể xé nhỏ ra và chấm với tương ớt nha. Từng sợi khô mực dai dai, mềm dẻo được vị ngọt thanh của nước dừa ôm trọn vào khiến hương vị vô cùng đậm đà mà vẫn dễ chịu, còn xen lẫn chút cay nồng của tương ớt nữa chứ. Đảm bảo ai mà ăn rồi là chỉ bị “ghiền” thôi đó.'),
(8, N'Khô Mực Giòn Muối Thái ', 160000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147771/HNAG/Food_KhoMuc/02.KhoMucGionMuoiThai.png', 100, N'Hộp 200gr. Khô mực chiên giòn khi kết hợp với những loại nước chấm khác nhau sẽ cho ra những hương vị khác biệt. Lớp vỏ giòn rụm, mực dai mềm hòa quyện với nước chấm đậm đà chắc chắn sẽ không làm bạn thất vọng.'),
(8, N'Khô Mực Cháy Tỏi Ớt', 65000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147773/HNAG/Food_KhoMuc/03.KhoMucChayToiOt.jpg', 100, N'Hũ 150gr. Khô mực cháy tỏi thành phẩm thơm ngào ngạt, vị đậm đà. Một chút cay cay hòa với vị mặn mà trong từng thớ thịt mực đảm bảo rằng cả nhà ai cũng thích. Món này có thể dùng kèm với bia, hoặc ăn chung với cơm trắng nóng hổi cũng rất bắt vị.'),
(8, N'Khô Mực Sợi Tẩm Vị ', 180000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147775/HNAG/Food_KhoMuc/04.KhoMucSoiTamVi.jpg', 100, N'Hũ 500gr. Mực xé sợi là món ăn liền tuyệt vời, thích hợp để thưởng thức lai rai bên các bàn nhậu. Không chỉ vậy, mực xé tẩm gia vị còn được nhiều người lựa chọn làm quà tặng đặc sản cho bạn bè, người thân sau các chuyến du lịch biển của mình. Nếu bạn là người thích hải sản và đặc biệt là món mực xé sợi. Dưới đây sẽ là những thông tin chi tiết giúp bạn hiểu hơn về món ăn “nức tiếng gần xa” này nhé.'),
(8, N'Khô Mực Sate Chua Cay', 100000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147778/HNAG/Food_KhoMuc/05.KhoMucSate.jpg', 100, N'Hũ 300gr. Mực rim ngọt cay mặn đậm đà, lá mực không quá dai, có thể dùng kèm với cơm hoặc làm đồ nhắm hay ăn vặt đều được. Nếu không ăn hết, bạn có thể bảo quản khô mực ở hũ, đậy kín và bảo quản ở nơi thoáng mát hoặc ngăn mát tủ lạnh.'),
(8, N'Khô Mực Cán Tẩm Vị', 220000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147782/HNAG/Food_KhoMuc/06.KhoMucCanTamVi.jpg', 100, N'Gói 200gr. Mực cán tẩm gia vị là đặc sản biển nổi tiếng được chế biến từ mực khô cao cấp. Với vị thịt mực ngọt thơm kết hợp công thức chế biến độc quyền, khô mực cán tẩm hiện đang là món ăn thu hút được lựa chọn nhiều tại HNAG. Hương vị đậm đà, khô mực cán phục vụ được số đông khách hàng từ kỹ tính đến khó tính, khách cả trong nước và thị trường xuất khẩu.'),
(8, N'Khô Mực Rang Muối Ớt ', 180000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147785/HNAG/Food_KhoMuc/07.KhoMucRangMuoiOt.jpg', 100, N'Hộp 180gr. Món mực rang muối ớt có mùi thơm hấp dẫn của tỏi ớt. Miếng mực vàng giòn, thấm đều gia vị khi đưa lên miệng cắn sẽ còn nghe tiếng "rắc rắc". Dùng món ăn làm mồi nhắm cho các bữa tiệc hoặc là món chính cho bữa cơm gia đình đều sẽ rất phù hợp.'),
(8, N'Khô Mực Tomyum Thái', 125000, N'http://res.cloudinary.com/db2vil8fw/image/upload/v1681147786/HNAG/Food_KhoMuc/08.KhoMucTomyum.jpg', 100, N'Hộp 250gr. Mực đựơc xé sợi tẩm sốt chanh tomyum , sấy dẻo khô sợi mực vàng ươm tự nhiên ko tẩm màu, có vị chua cay ngọt ngọt mằn mặn hoà nguyện cùng mùi thơm từ tinh dầu của vỏ chanh mà lại chấm cùng sốt béo nữa vừa dụ miệng vừa bắt mồi ngay từ cái thử vị đầu tiên xem thế nào.')